namespace BankAccountApp
{
    partial class UC_QuanLiNganSach
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing){ if (disposing && (components!=null)) components.Dispose(); base.Dispose(disposing); }

        private System.Windows.Forms.Panel header;
        private System.Windows.Forms.Label lblTitle;
        private System.Windows.Forms.TabControl tab;
        private System.Windows.Forms.TabPage tabBudget;
        private System.Windows.Forms.TabPage tabTx;
        private System.Windows.Forms.DataGridView dgvBudgets;
        private System.Windows.Forms.DataGridView dgvTx;
        private System.Windows.Forms.FlowLayoutPanel toolBud;
        private System.Windows.Forms.Button btnAddBud;
        private System.Windows.Forms.Button btnDelBud;
        private System.Windows.Forms.Button btnImpBud;
        private System.Windows.Forms.Button btnExpBud;
        private System.Windows.Forms.FlowLayoutPanel toolTx;
        private System.Windows.Forms.Button btnAddT;
        private System.Windows.Forms.Button btnDelT;
        private System.Windows.Forms.Button btnImpT;
        private System.Windows.Forms.Button btnExpT;
        private System.Windows.Forms.Panel sumBar;
        private System.Windows.Forms.Panel card1;
        private System.Windows.Forms.Panel card2;
        private System.Windows.Forms.Panel card3;
        private System.Windows.Forms.Label lbl1;
        private System.Windows.Forms.Label lbl2;
        private System.Windows.Forms.Label lbl3;
        private System.Windows.Forms.Label lblLimit;
        private System.Windows.Forms.Label lblSpent;
        private System.Windows.Forms.Label lblLeft;
        private System.Windows.Forms.ProgressBar pb;
        private System.Windows.Forms.Panel chartHost;
        private System.Windows.Forms.Panel budgetChart;
        private System.Windows.Forms.FlowLayoutPanel filterBar;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.DateTimePicker dtFrom;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.DateTimePicker dtTo;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.ComboBox cboCat;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.TextBox txtSearch;
        private System.Windows.Forms.FlowLayoutPanel flowChips;

        private void InitializeComponent()
        {
            this.header = new System.Windows.Forms.Panel();
            this.lblTitle = new System.Windows.Forms.Label();
            this.tab = new System.Windows.Forms.TabControl();
            this.tabBudget = new System.Windows.Forms.TabPage();
            this.dgvBudgets = new System.Windows.Forms.DataGridView();
            this.chartHost = new System.Windows.Forms.Panel();
            this.budgetChart = new System.Windows.Forms.Panel();
            this.sumBar = new System.Windows.Forms.Panel();
            this.card1 = new System.Windows.Forms.Panel();
            this.lbl1 = new System.Windows.Forms.Label();
            this.lblLimit = new System.Windows.Forms.Label();
            this.card2 = new System.Windows.Forms.Panel();
            this.lbl2 = new System.Windows.Forms.Label();
            this.lblSpent = new System.Windows.Forms.Label();
            this.card3 = new System.Windows.Forms.Panel();
            this.lbl3 = new System.Windows.Forms.Label();
            this.lblLeft = new System.Windows.Forms.Label();
            this.pb = new System.Windows.Forms.ProgressBar();
            this.toolBud = new System.Windows.Forms.FlowLayoutPanel();
            this.btnAddBud = new System.Windows.Forms.Button();
            this.btnDelBud = new System.Windows.Forms.Button();
            this.btnImpBud = new System.Windows.Forms.Button();
            this.btnExpBud = new System.Windows.Forms.Button();
            this.tabTx = new System.Windows.Forms.TabPage();
            this.dgvTx = new System.Windows.Forms.DataGridView();
            this.toolTx = new System.Windows.Forms.FlowLayoutPanel();
            this.btnAddT = new System.Windows.Forms.Button();
            this.btnDelT = new System.Windows.Forms.Button();
            this.btnImpT = new System.Windows.Forms.Button();
            this.btnExpT = new System.Windows.Forms.Button();
            this.filterBar = new System.Windows.Forms.FlowLayoutPanel();
            this.label1 = new System.Windows.Forms.Label();
            this.dtFrom = new System.Windows.Forms.DateTimePicker();
            this.label2 = new System.Windows.Forms.Label();
            this.dtTo = new System.Windows.Forms.DateTimePicker();
            this.label3 = new System.Windows.Forms.Label();
            this.cboCat = new System.Windows.Forms.ComboBox();
            this.label4 = new System.Windows.Forms.Label();
            this.txtSearch = new System.Windows.Forms.TextBox();
            this.flowChips = new System.Windows.Forms.FlowLayoutPanel();
            this.header.SuspendLayout();
            this.tab.SuspendLayout();
            this.tabBudget.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvBudgets)).BeginInit();
            this.chartHost.SuspendLayout();
            this.sumBar.SuspendLayout();
            this.card1.SuspendLayout();
            this.card2.SuspendLayout();
            this.card3.SuspendLayout();
            this.toolBud.SuspendLayout();
            this.tabTx.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvTx)).BeginInit();
            this.toolTx.SuspendLayout();
            this.filterBar.SuspendLayout();
            this.SuspendLayout();
            this.header.Dock = System.Windows.Forms.DockStyle.Top;
            this.header.Height = 52;
            this.header.BackColor = System.Drawing.Color.FromArgb(52,120,246);
            this.header.Controls.Add(this.lblTitle);
            this.lblTitle.Text = "Quản lý Ngân sách";
            this.lblTitle.ForeColor = System.Drawing.Color.White;
            this.lblTitle.Font = new System.Drawing.Font("Segoe UI Semibold", 13F);
            this.lblTitle.AutoSize = true;
            this.lblTitle.Location = new System.Drawing.Point(14, 12);
            this.tab.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tab.Controls.Add(this.tabBudget);
            this.tab.Controls.Add(this.tabTx);
            this.tabBudget.Text = "Ngân sách";
            this.tabBudget.Padding = new System.Windows.Forms.Padding(10);
            this.tabBudget.Controls.Add(this.dgvBudgets);
            this.tabBudget.Controls.Add(this.chartHost);
            this.tabBudget.Controls.Add(this.sumBar);
            this.tabBudget.Controls.Add(this.toolBud);
            this.toolBud.Dock = System.Windows.Forms.DockStyle.Top;
            this.toolBud.Height = 40;
            this.toolBud.Padding = new System.Windows.Forms.Padding(10,6,10,6);
            this.toolBud.BackColor = System.Drawing.Color.White;
            this.toolBud.Controls.Add(this.btnAddBud);
            this.toolBud.Controls.Add(this.btnDelBud);
            this.toolBud.Controls.Add(this.btnImpBud);
            this.toolBud.Controls.Add(this.btnExpBud);
         
            this.btnAddBud.Click += new System.EventHandler(this.BtnAddBudget_Click);
            this.btnDelBud.Click += new System.EventHandler(this.BtnDelBudget_Click);
            this.btnImpBud.Click += new System.EventHandler(this.BtnImportBudget_Click);
            this.btnExpBud.Click += new System.EventHandler(this.BtnExportBudget_Click);
            this.sumBar.Dock = System.Windows.Forms.DockStyle.Top;
            this.sumBar.Height = 92;
            this.sumBar.Padding = new System.Windows.Forms.Padding(10);
            this.sumBar.BackColor = System.Drawing.Color.White;
            this.sumBar.Controls.Add(this.card1);
            this.sumBar.Controls.Add(this.card2);
            this.sumBar.Controls.Add(this.card3);
            this.sumBar.Controls.Add(this.pb);
          
            this.pb.Width = 300; this.pb.Height = 10;
            this.pb.Style = System.Windows.Forms.ProgressBarStyle.Continuous;
            this.pb.Margin = new System.Windows.Forms.Padding(10,26,10,10);
            this.pb.Maximum = 100; this.pb.Value = 0;
            this.chartHost.Dock = System.Windows.Forms.DockStyle.Right;
            this.chartHost.Width = 260;
            this.chartHost.Padding = new System.Windows.Forms.Padding(10,10,0,0);
            this.chartHost.BackColor = System.Drawing.Color.White;
            this.chartHost.Controls.Add(this.budgetChart);
            this.budgetChart.Dock = System.Windows.Forms.DockStyle.Fill;
            this.budgetChart.BackColor = System.Drawing.Color.White;
            this.dgvBudgets.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabTx.Text = "Giao dịch";
            this.tabTx.Padding = new System.Windows.Forms.Padding(10);
            this.tabTx.Controls.Add(this.dgvTx);
            this.tabTx.Controls.Add(this.toolTx);
            this.tabTx.Controls.Add(this.filterBar);
            this.filterBar.Dock = System.Windows.Forms.DockStyle.Top;
            this.filterBar.Height = 44;
            this.filterBar.Padding = new System.Windows.Forms.Padding(10,6,10,6);
            this.filterBar.BackColor = System.Drawing.Color.White;
            this.filterBar.Controls.Add(this.label1);
            this.filterBar.Controls.Add(this.dtFrom);
            this.filterBar.Controls.Add(this.label2);
            this.filterBar.Controls.Add(this.dtTo);
            this.filterBar.Controls.Add(this.label3);
            this.filterBar.Controls.Add(this.cboCat);
            this.filterBar.Controls.Add(this.label4);
            this.filterBar.Controls.Add(this.txtSearch);
            this.filterBar.Controls.Add(this.flowChips);
            this.label1.AutoSize = true; this.label1.Text = "Từ:"; this.label1.Margin = new System.Windows.Forms.Padding(0,8,6,0);
            this.dtFrom.Format = System.Windows.Forms.DateTimePickerFormat.Short; this.dtFrom.Width = 110; this.dtFrom.Margin = new System.Windows.Forms.Padding(0,4,12,0);
            this.dtFrom.ValueChanged += new System.EventHandler(this.ApplyTxFilter);
            this.label2.AutoSize = true; this.label2.Text = "→"; this.label2.Margin = new System.Windows.Forms.Padding(0,8,6,0);
            this.dtTo.Format = System.Windows.Forms.DateTimePickerFormat.Short; this.dtTo.Width = 110; this.dtTo.Margin = new System.Windows.Forms.Padding(0,4,12,0);
            this.dtTo.ValueChanged += new System.EventHandler(this.ApplyTxFilter);
            this.label3.AutoSize = true; this.label3.Text = "Mục:"; this.label3.Margin = new System.Windows.Forms.Padding(0,8,6,0);
            this.cboCat.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList; this.cboCat.Width = 150; this.cboCat.Margin = new System.Windows.Forms.Padding(0,4,12,0);
            this.cboCat.Items.AddRange(new object[]{"Tất cả","Ăn uống","Đi lại","Giải trí","Khác"});
            this.cboCat.SelectedIndex = 0; this.cboCat.SelectedIndexChanged += new System.EventHandler(this.ApplyTxFilter);
            this.label4.AutoSize = true; this.label4.Text = "Tìm:"; this.label4.Margin = new System.Windows.Forms.Padding(0,8,6,0);
            this.txtSearch.Width = 160; this.txtSearch.Margin = new System.Windows.Forms.Padding(0,4,12,0);
            this.txtSearch.TextChanged += new System.EventHandler(this.ApplyTxFilter);
            this.flowChips.AutoSize = true; this.flowChips.Margin = new System.Windows.Forms.Padding(6,2,2,2);
            this.toolTx.Dock = System.Windows.Forms.DockStyle.Top;
            this.toolTx.Height = 40;
            this.toolTx.Padding = new System.Windows.Forms.Padding(10,6,10,6);
            this.toolTx.BackColor = System.Drawing.Color.White;
            this.toolTx.Controls.Add(this.btnAddT);
            this.toolTx.Controls.Add(this.btnDelT);
            this.toolTx.Controls.Add(this.btnImpT);
            this.toolTx.Controls.Add(this.btnExpT);
            System.Action<System.Windows.Forms.Button,string> StyleBtn2 = (b,text)=>{
                b.Text = text; b.AutoSize = true; b.BackColor = System.Drawing.Color.White;
                b.ForeColor = System.Drawing.Color.FromArgb(52,120,246); b.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
                b.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(52,120,246); b.FlatAppearance.BorderSize = 1;
                b.Margin = new System.Windows.Forms.Padding(0,2,8,2); b.Font = new System.Drawing.Font("Segoe UI", 9f);
            };
            StyleBtn2(this.btnAddT,"Thêm GD");
            StyleBtn2(this.btnDelT,"Xóa GD");
            StyleBtn2(this.btnImpT,"Nhập CSV");
            StyleBtn2(this.btnExpT,"Xuất CSV");
            this.btnAddT.Click += new System.EventHandler(this.BtnAddTx_Click);
            this.btnDelT.Click += new System.EventHandler(this.BtnDelTx_Click);
            this.btnImpT.Click += new System.EventHandler(this.BtnImportTx_Click);
            this.btnExpT.Click += new System.EventHandler(this.BtnExportTx_Click);
            this.dgvTx.Dock = System.Windows.Forms.DockStyle.Fill;
            this.Controls.Add(this.tab);
            this.Controls.Add(this.header);
            this.Name = "UC_QuanLiNganSach";
            this.Size = new System.Drawing.Size(1080, 640);
            this.header.ResumeLayout(false);
            this.header.PerformLayout();
            this.tab.ResumeLayout(false);
            this.tabBudget.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dgvBudgets)).EndInit();
            this.chartHost.ResumeLayout(false);
            this.sumBar.ResumeLayout(false);
            this.card1.ResumeLayout(false);
            this.card1.PerformLayout();
            this.card2.ResumeLayout(false);
            this.card2.PerformLayout();
            this.card3.ResumeLayout(false);
            this.card3.PerformLayout();
            this.toolBud.ResumeLayout(false);
            this.toolBud.PerformLayout();
            this.tabTx.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dgvTx)).EndInit();
            this.toolTx.ResumeLayout(false);
            this.toolTx.PerformLayout();
            this.filterBar.ResumeLayout(false);
            this.filterBar.PerformLayout();
            this.ResumeLayout(false);
        }
    }
}
